import math

MOUSE_SENSIITY = 0.003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = 1200 - MOUSE_BORDER_LEFT

FOV = math.pi / 4
HALF_FOV = FOV / 2
NUM_RAYS = 1200 // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = (1200 // 2) / math.tan(HALF_FOV)
SCALE = 1200 // NUM_RAYS
TEXTURE_SIZE = 225
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2